version: '3'
services:
  front:
    build:
      context: frontend
     # dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "8000:80"
    networks:
      - wewaa-network

  backend:
    build:
      context: backend
    container_name: backend
    environment:
      spring.datasource.url: "jdbc:mysql://mysqldb:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true&createDatabaseIfNotExist=true"
#      MYSQL_CONNECTION_URI: "jdbc:mysql://mysql-database:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true&createDatabaseIfNotExist=true"
#      MYSQL_ROOT_PASSWORD: "ce19f003"
#      MYSQL_USER: "root"
#      MYSQL_DATABASE: "test_db"
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - wewaa-network

  text2image:
    build:
      context: ./text2image
    container_name: text2image
    ports:
      - "5000:5000"
    networks:
      - wewaa-network

  mysql:
    image: mysql:5.7
    hostname: mysqldb
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: ce19f003
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./db/data/wewaa:/var/lib/mysql/wewaa
    expose:
      - 3306
    networks:
      - wewaa-network

networks:
  wewaa-network:
    driver: bridge
