version: '3'
services:
# dev 환경에서는 필요 없음
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    depends_on:
#      - frontend
#    ports:
#      - 80:80
#    volumes:
#      - ./nginx/config:/etc/nginx/conf.d:ro
#    networks:
#      - nginx-tier

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
#    expose:
#      - "3000"
    volumes:
      - ./frontend:/app
    networks:
      - nginx-tier
      - frontend-tier

  backend:
    container_name: backend
    build: ./backend
    depends_on:
      - mysqldb
    expose:
      - "8080"
    environment:
      spring.datasource.url: "jdbc:mysql://mysqldb:3306/wewaa?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true"
    volumes:
      - ./backend:/backend
    networks:
      - db-tier
      - ai-tier
      - frontend-tier
    tty: true

  text2image:
    container_name: text2image
    build: ./text2image
    expose:
      - "5000"
    networks:
      - db-tier
      - ai-tier

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: wewaa
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./db/wewaa:/var/lib/wewaa
    ports:
      - 3306:3306
    networks:
      - db-tier

#  adminer:
#    image: adminer
#    container_name: adminer
#    restart: always
#    environment:
#      ADMINER_DEFAULT_SERVER: mysqldb
#      ADMINER_DESIGN: ce19f003
#      ADMINER_PASSWORD: 0000
#      ADMINER_USERNAME: root
#    ports:
#      - "8081:8080"
#    networks:
#      - nginx-tier

networks:
  db-tier:
    driver: bridge
  nginx-tier:
    driver: bridge
  ai-tier:
    driver: bridge
  frontend-tier:
    driver: bridge
