version: '3'
services:
# dev 환경에서는 필요 없음
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    depends_on:
#      - frontend
#    ports:
#      - 80:80
#    volumes:
#      - ./nginx/config:/etc/nginx/conf.d:ro
#    networks:
#      - nginx-tier

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
#    expose:
#      - "3000"
    volumes:
      - ./frontend:/app
    networks:
      - nginx-tier
      - frontend-tier

  backend:
    container_name: backend
    build: ./backend
    depends_on:
      - mysqldb
    expose:
      - "8080"
    environment:
      spring.datasource.url: "jdbc:mysql://mysqldb:3306/wewaa?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true"
    volumes:
      - ./backend:/backend
    networks:
      - db-tier
      - ai-tier
      - frontend-tier
    tty: true

  text2image:
    build: ./text2image
    # dockerfile: Dockerfile.test
    container_name: text2image
    privileged: true
    cap_add:
      - ALL #unsure if necessary
    environment:
      - TPU_NAME=tpu_name
      - TF_CPP_MIN_LOG_LEVEL=0
      - XRT_TPU_CONFIG="localservice;0;localhost:51011"
      - TF_XLA_FLAGS=--tf_xla_enable_xla_devices
    volumes:
      - ./text2image:/dalle
      - /var/run/docker.sock:/var/run/docker.sock #unsure if necessary
      - /usr/share/tpu/:/usr/share/tpu/
      - /lib/libtpu.so:/lib/libtpu.so
    devices:
      - "/dev:/dev"
    tty: true
    env_file:
      - ./env.env
    ports:
      - "80:80"

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: on-failure
    environment:
      MYSQL_DATABASE: wewaa
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_ROOT_HOST: '%'
#    volumes:
#      - ./db/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    networks:
      - db-tier

  mongodb:
    image: mongo
    container_name: mongodb
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: wewaa
      MONGO_INITDB_ROOT_PASSWORD: wewaa
      MONGO_INITDB_DATABASE: wewaa
    networks:
      - db-tier
    tty: true

  mongo-express:
    image: mongo-express
    container_name: mongo_admin
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: wewaa
      ME_CONFIG_MONGODB_ADMINPASSWORD: wewaa
    networks:
      - db-tier
    tty: true
#  adminer:
#    image: adminer
#    container_name: adminer
#    restart: always
#    environment:
#      ADMINER_DEFAULT_SERVER: mysqldb
#      ADMINER_DESIGN: ce19f003
#      ADMINER_PASSWORD: 0000
#      ADMINER_USERNAME: root
#    ports:
#      - "8081:8080"
#    networks:
#      - nginx-tier

networks:
  db-tier:
    driver: bridge
  nginx-tier:
    driver: bridge
  ai-tier:
    driver: bridge
  frontend-tier:
    driver: bridge
