version: '3'
services:
  :
    build: ./frontend
     # dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "8000:80"
    networks:
      - wewaa-network

  backend:
    build:
      context: backend
    container_name: backend
    environment:
      spring.datasource.url: "jdbc:mysql://mysqldb:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true"
#      MYSQL_CONNECTION_URI: "jdbc:mysql://mysql-database:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true&createDatabaseIfNotExist=true"
#      MYSQL_ROOT_PASSWORD: "ce19f003"
#      MYSQL_USER: "root"
#      MYSQL_DATABASE: "test_db"
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"
    networks:
      - wewaa-network

  text2image:
    build:
      context: ./text2image
    container_name: text2image
    ports:
      - "5000:5000"
    networks:
      - wewaa-network

  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wewaa
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./db/data/wewaa:/var/lib/mysql/wewaa
    expose:
      - 3306
    networks:
      - db-tier

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
networks:
  db-tier:
    driver: bridge
